### ISSUE TITLE
Issue with NovaBackButton class in VSCode

### ISSUE THREAD

**Issue by spire-mike** [SLASH2NL/nova-back-button#1]
@jeffreyzant thanks for this package!

Have you seen any issues using it with VSCode? For some reason it keeps telling me that it doesn't recognize the class:

![image](https://user-images.githubusercontent.com/77629408/145317353-4f39db81-3e89-4935-9df6-c8d39b8056a4.png)

Even though you can see it is imported at the top of the file:

![image](https://user-images.githubusercontent.com/77629408/145317399-e38d04e4-4c6e-4c74-966c-529110b2a990.png)

Any idea what would cause that? It seems to be functioning correctly despite the VSCode error.

**Comment by spire-mike** [comment]
Could it possibly just be because `SLASH2NL` is all caps? Maybe that confuses intellisense somehow?

**Comment by jeffreyzant** [comment]
Hi @spire-mike which intellisense plugin are you using in VSCode? We are not seeing any issues with the PHP Intelephense plugin at v1.8.0. Sometimes after installing a new package it helps to restart VSCode which results in rescanning the project. Normally that fixes these Undefined type errors

**Comment by spire-mike** [comment]
@jeffreyzant - thanks for getting back to me. Yea it seems all I had to do was run the "Index Workspace" command, and the error went away.
