### ISSUE TITLE
Nova 4 back button

### ISSUE THREAD

**Issue by philipbaginski** [SLASH2NL/nova-back-button#2]
Hi,

The question I have: I would like to see the button only on detail view and want to go back to index view after edit view.

If I use e.g. ->url('/resources/users') it gives 404 error as popup, and nothing else happened on the webpage.

How to make it work?

**Comment by jeffreyzant** [comment]
Hi Philip.

I'm not sure if I fully understand your question. But the back-button does not show on the edit page. If you want to redirect back to the index view after submitting an edit you can use the default nova method "redirectAfterUpdate".

For the ->url() method on this back-button. If you are using the /nova in your url you should enter ->url('/nova/resources/users').
