### ISSUE TITLE
I cannot see the Back Button

### ISSUE THREAD

**Issue by macorredor** [SLASH2NL/nova-back-button#3]
I have added the composer package. I have followed the usage steps. But I cannot see the button on the Resource page.
But if I open the inspector I can see this:

`<nova-back-button class="md:col-span-12 h-full" card="[object Object]" resource="[object Object]" resourcename="users" resourceid="1" lens=""></nova-back-button>`

I am using Laravel Nova 4.7.0. And nova-back-button 2.0.2.

Could you help me, please? Thanks in advance.

**Comment by jeffreyzant** [comment]
Hi there!

Could you please provide an example for the code your using inside the cards() method?

**Comment by jeffreyzant** [comment]
The <nova-back-button> component should be replaced for a normal div with classes in your element inspector. This could indicate that you have some kind of JS error on the page. This can be from incorrect configuration of the back-button or some other component.

**Comment by macorredor** [comment]
Hi there!
Thanks for your quick answer.
There was an error on my server with the composer command. I just tested on my local machine and it worked perfectly. I then uploaded the vendor folder manually and now it is working.
My apologies...
