### ISSUE TITLE
Call to undefined method SLASH2NL\NovaBackButton\NovaBackButton::isShownOnDetail()

### ISSUE THREAD

**Issue by mateusgalasso** [SLASH2NL/nova-back-button#5]
Call to undefined method SLASH2NL\NovaBackButton\NovaBackButton::isShownOnDetail()

**Comment by jeffreyzant** [comment]
There's not much information here, but I think you are using it as a field and not as a card. If that is not correct please feel free to post some additional code so I can reproduce the issue.
