### ISSUE TITLE
Nova 5

### ISSUE THREAD

**Issue by adrian-schnell** [SLASH2NL/nova-back-button#7]
Hi!

Thanks for the awesome package! Are there plans for Nova 5 compatibility?

**Comment by jeffreyzant** [comment]
Hey,

I’ll have a look at it tomorrow!

**Comment by jeffreyzant** [comment]
Support for Nova 5 is now added in 2.1.0, looks like it did not require any real changes so it's backwards compatible. If anyone sees something weird please let me know!
